### PR TITLE
017: Data Analytics (Backend)

### PR DESCRIPTION
**Pull request by ZackFiner**
As a frontend developer, I need a way to retrieve data analytics about open tickets so I build a UI for viewing this information.

### CODE REVIEW

**Comment by ZackFiner** [comment]
The format i've been using is YYYY-MM-DD hh:mm:ss. I haven't tried it, but the format returned by momeny for ISOString is something like this 2019-01-06T08:57:30.000Z

**Comment by ZackFiner** [comment]
Actually, i just realized axios doesn't support sending get requests with a json body. So i'm going to switch that function to use the request query (url parameters) instead of anything in the body.

**Comment by antoinengu** [comment]
Yep, I learned that too when doing the login attempts backend. You can check that for reference if you need to.

**Comment by antoinengu** [comment]
looks good. fix merge conflicts, do a quick test, then merge.

**Pull request merged**
