### PR TITLE
routing for user registration

### PR DESCRIPTION
**Pull request by ZackFiner**

### CODE REVIEW

**Comment by antoinengu** [comment]
Shouldn't the frontend be solely responsible for verifying the password requirement criteria? It's the one that has to display an error message to the user if it does not comply. Only if the the password matches the criteria does the frontend call the Express route to register the user.

**Comment by ZackFiner** [comment]
I think the back-end also needs to check to see if the password meets the criteria. Otherwise, someone using postman could just bypass the password checks by manually editing the JSON for the request. Front end will also check, and it will be able to provide more descriptive error messages.

**Comment by ZackFiner** [comment]
I've moved the story to verification. To test the code, open postman and setup a request to the following URL:
http://localhost:5000/api/users

In the headers section, make sure that the Content-Type is set to application/json

For the body, raw should be selected, and JSON should be selected from the drop down.
An example request looks something like this:
{
    "email":"some.email@email.com",
    "password":"passsW0rd$",
    "username":"Username"
}

**Comment by DaleCS** [comment]
> Shouldn't the frontend be solely responsible for verifying the password requirement criteria? It's the one that has to display an error message to the user if it does not comply. Only if the the password matches the criteria does the frontend call the Express route to register the user.

Don't know how most sites/apps do it but according to professor Fabio, both frontend and backend should validate user input. iirc he said that the server shouldn't trust the client, and the client shouldn't trust the user or some shiz like that.

**Pull request merged**
