### PR TITLE
013: Create, Update, Delete Comments (Backend)

### PR DESCRIPTION
**Pull request by DaleCS**
As a frontend developer, I need to be able to create, update, delete comments owned by a user so that I can build a UI for managing comments.

### CODE REVIEW

**Comment by DaleCS** [comment]
What I did:
_ Created a route for creating comments that takes ticket_id, author_id, and content_text as body keys.
_ Created a route for updating comments that takes comment_id, and content_text as body keys.
_ Created a route for deleting comments that takes comment_id as body key.

How to test:
_ Test the create route using POST on "http://localhost:5000/api/tickets/comments/create" and setting ticket_id, author_id to existing tickets and users as well as content_text to the contents of the the comment. Check the changes using MySQL workbench.
_ Test the update/edit route using PUT on "http://localhost:5000/api/tickets/comments" and setting comment_id to an existing comment and content_text to the text you want to replace the existing content_text. Check the changes using MySQL workbench.
_ Test the delete route using DELETE on "http://localhost:5000/api/tickets/comments" and setting comment_id to the an existing comment. Check the changes using MySQL workbench.

**Comment by DaleCS** [comment]
Creating tickets can now optionally change the embedded ticket's current_status, priority, protected_status by adding those values to the request object.

An example of a new comment that changes the ticket's current_status, priority, and protected status is this:

const newTicket = {
   ticket_id: 1, 
   author_id: 1, 
   content_text: "AWDJAWD", 
   current_status: "WIP", 
   priority: 4, 
   protected_status: true
};

**Comment by antoinengu** [comment]
Can you add the the option to set the assignee of the ticket?

**Comment by DaleCS** [comment]
> Can you add the the option to set the assignee of the ticket?

Added. The create route now optionally accepts 'assignee' which is the assignee's user_id. 

If the ticket had already been previously assigned to someone else, it will replace the existing assignee to the new assignee. (I'm assuming only one person can be assigned to a ticket)

If there is no assignee, a new tuple is added to userassignment table for the assignee.

**Pull request merged**
