### PR TITLE
006: User Dashboard (Frontend)

### PR DESCRIPTION
**Pull request by DaleCS**
User story description:
As a user, I want to be presented a dashboard that shows me what tickets I've created or been assigned to, what team(s) I'm assigned to, and previous comments that I've made so that I have an overview of my tasks.

### CODE REVIEW

**Comment by antoinengu** [comment]
https://github.com/gregnb/mui-datatables/blob/master/README.md

This seems like a component that will do 90% of everything we need for the dashboard. Has built in sorting and filtering.

**Comment by DaleCS** [comment]
> https://github.com/gregnb/mui-datatables/blob/master/README.md
> 
> This seems like a component that will do 90% of everything we need for the dashboard. Has built in sorting and filtering.

Thanks, I'll take a look at it.

**Comment by DaleCS** [comment]
How to test:
Log in and browse to "/dashboard". If you have tickets created/assigned to your account, they will show up in /dashboard. Each ticket is clickable, and will open a modal showing its detailed information as well as comments.

**Comment by DaleCS** [comment]
I moved this back to in-progress because it requires additional backend functionalities (Fetch comments, fetch teams) in order to be completed.

**Pull request merged**
